version: 2

shared: &shared
  working_directory: ~/repo

  steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: npm config set unsafe-perm=true
    - run: yarn install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run: yarn prettier --list-different
    - run: yarn test
    - run: yarn test:e2e


jobs:
  "node-10":
    <<: *shared
    docker:
      - image: node:10
  "node-11":
    <<: *shared
    docker:
      - image: node:11

workflows:
  version: 2
  build:
    jobs:
      - "node-10"
      - "node-11"
  nightly:
    jobs:
      - "node-10"
      - "node-11"
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
